#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME - the root directory of dotfiles.
cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

echo "Symlinking i3blocks by Anachron"
ln -sf $HOME/.yadm/submodules/anachron-i3blocks/blocks .config/i3blocks
